---
name: cf
director_uuid: 4b9e557d-9064-4f49-97cb-fcca7969a11a

releases:
 - name: cf
   version: 146
 - name: services-contrib
   version: latest
 - name: admin-ui
   version: latest

networks:
  - name: floating
    type: vip
    cloud_properties:
      net_id: 7c5db1d2-11dc-4183-aed1-a6487b0e7e41
  - name: fluffy
    type: dynamic
    cloud_properties:
      net_id: 0694055f-d310-4979-a8cc-4b1b3bc86ac4 # CHANGE
  - name: default
    type: manual
    subnets:
      - name: private
        range: 10.2.3.0/24 # CHANGE
        gateway: 10.2.3.1 # CHANGE
        reserved:
          - 10.2.3.2 - 10.2.3.150 # CHANGE
        static:
          - 10.2.3.200 - 10.2.3.230 # CHANGE
        cloud_properties:
          net_id: 0694055f-d310-4979-a8cc-4b1b3bc86ac4 # CHANGE
          security_groups:
            - default

update:
  canaries: 1
  canary_watch_time: 30000-60000
  update_watch_time: 30000-60000
  max_in_flight: 4

compilation:
  workers: 2
  network: default
  reuse_compilation_vms: true
  cloud_properties:
    instance_type: m1.medium
    net_id: 0694055f-d310-4979-a8cc-4b1b3bc86ac4

resource_pools:
  - name: small
    network: default
    size: 6
    stemcell:
      name: bosh-openstack-kvm-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.small

  - name: dea
    network: default
    size: 4
    stemcell:
      name: bosh-openstack-kvm-ubuntu
      version: latest
    cloud_properties:
      instance_type: m1.medium

jobs:
  - name: data
    release: cf
    template:
      - postgres
      - debian_nfs_server
    instances: 1
    resource_pool: small
    persistent_disk: 10240
    networks:
    - name: default
      default:
      - dns
      - gateway
    properties:
      db: databases

  - name: core
    release: cf
    template:
      - nats
      - health_manager_next
      - uaa
    instances: 1
    resource_pool: small
    networks:
    - name: default
      default:
      - dns
      - gateway

  - name: api
    release: cf
    template:
      - cloud_controller_ng
      - gorouter
    instances: 1
    resource_pool: small
    networks:
    - name: default
      default:
      - dns
      - gateway
    - name: floating
      static_ips:
      - 205.234.30.249
    properties:
      db: databases

  - name: dea
    release: cf
    template:
      - dea_next
    instances: 4
    resource_pool: dea
    networks:
      - name: default
        default: [dns, gateway]

  - name: gateways
    release: services-contrib
    template:
    - rabbit_gateway
    instances: 1
    resource_pool: small
    networks:
      - name: default
        default: [dns, gateway]

  - name: rabbit_service_node
    release: services-contrib
    template: rabbit_node_ng
    instances: 1
    resource_pool: small
    persistent_disk: 10000
    properties:
      plan: default
    networks:
      - name: default
        default: [dns, gateway]
        static_ips:
          - 10.2.3.201

  - name: admin_ui
    persistent_disk: 4096
    release: admin-ui
    instances: 1
    resource_pool: small
    template: admin_ui
    networks:
      - name: default
        default: [dns, gateway]

properties:
  cf:
    name: cf
    dns: somegood.org
    ip_addresses: ["205.234.30.249"]
    deployment_size: medium
    security_group: cf
    persistent_disk: 10240
    common_password: admin
    dea_server_ram: 1500

  domain: somegood.org
  system_domain: somegood.org
  system_domain_organization: system_domain
  app_domains:
    - somegood.org

  networks:
    apps: default
    management: default

  nats:
    address: 0.core.default.cf.microbosh
    port: 4222
    user: nats
    password: admin
    authorization_timeout: 6    

  router:
    port: 8081
    status:
      port: 8080
      user: gorouter
      password: admin

  dea: &dea
    memory_mb: 15000
    disk_mb: 102400
    directory_server_protocol: http

  dea_next: *dea

  syslog_aggregator:
    address: 0.syslog-aggregator.default.cf.microbosh
    port: 54321

  nfs_server:
    address: 0.data.default.cf.microbosh
    network: "*.cf.microbosh"
    idmapd_domain: somegood.org

  debian_nfs_server:
    no_root_squash: true

  databases: &databases
    db_scheme: postgres
    address: 0.data.default.cf.microbosh
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true
      - tag: uaa
        name: uaadb
        citext: true

  ccdb: &ccdb
    db_scheme: postgres
    address: 0.data.default.cf.microbosh
    port: 5524
    roles:
      - tag: admin
        name: ccadmin
        password: admin
    databases:
      - tag: cc
        name: ccdb
        citext: true

  ccdb_ng: *ccdb

  uaadb: 
    db_scheme: postgresql
    address: 0.data.default.cf.microbosh
    port: 5524
    roles:
      - tag: admin
        name: uaaadmin
        password: admin
    databases:
      - tag: uaa
        name: uaadb
        citext: true

  # Service credentials
  uaa_client_id: "cf"
  uaa_endpoint: http://uaa.somegood.org #http://0.core.default.cf.microbosh:8080
  uaa_client_auth_credentials:
    username: services
    password: admin

  service_plans:
    rabbit:
      default:
        description: "Developer, 250MB storage, 10 connections"
        free: true
        job_management:
          high_water: 230 
          low_water: 20
        configuration:
          capacity: 125 
          max_clients: 10
          quota_files: 4
          quota_data_size: 240 
          enable_journaling: true
          backup:
            enable: false
          lifecycle:
            enable: false
            serialization: enable
            snapshot:
              quota: 1

  # rabbit props
  rabbit_gateway:
    token: xo2eiYait3eighu4oof3Ziereb8reete
    default_plan: "default"
    supported_versions: ["3.0"]
    version_aliases:
      current: "3.0"
    cc_api_version: v2
  rabbit_node:
    supported_versions: ["3.0"]
    default_version: "3.0"
    max_tmp: 900

  cc_api_version: v2

  admin_ui:
    cloud_controller_uri: http://api.somegood.org
    uaa_admin_credentials:
      username: admin
      password: admin
    ui_admin_credentials:
      username: admin
      password: passw0rd
    ui_credentials:
      username: user
      password: passw0rd
    uri: admin.somegood.org

  cc: &cc
    logging_level: debug
    external_host: api
    srv_api_uri: http://api.somegood.org
    cc_partition: default
    db_encryption_key: admin
    bootstrap_admin_email: admin@somegood.org
    bulk_api_password: admin
    uaa_resource_id: cloud_controller
    staging_upload_user: uploaduser
    staging_upload_password: admin
    resource_pool:
      resource_directory_key: cc-resources
      # Local provider when using NFS
      fog_connection:
        provider: Local
    packages:
      app_package_directory_key: cc-packages
    droplets:
      droplet_directory_key: cc-droplets
    default_quota_definition: runaway

  ccng: *cc

  login:
    enabled: false

  uaa:
    url: http://uaa.somegood.org
    spring_profiles: postgresql
    no_ssl: true
    catalina_opts: -Xmx768m -XX:MaxPermSize=256m
    resource_id: account_manager
    jwt:
      signing_key: |
        -----BEGIN RSA PRIVATE KEY-----
        MIICXAIBAAKBgQDHFr+KICms+tuT1OXJwhCUmR2dKVy7psa8xzElSyzqx7oJyfJ1
        JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMXqHxf+ZH9BL1gk9Y6kCnbM5R6
        0gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBugspULZVNRxq7veq/fzwIDAQAB
        AoGBAJ8dRTQFhIllbHx4GLbpTQsWXJ6w4hZvskJKCLM/o8R4n+0W45pQ1xEiYKdA
        Z/DRcnjltylRImBD8XuLL8iYOQSZXNMb1h3g5/UGbUXLmCgQLOUUlnYt34QOQm+0
        KvUqfMSFBbKMsYBAoQmNdTHBaz3dZa8ON9hh/f5TT8u0OWNRAkEA5opzsIXv+52J
        duc1VGyX3SwlxiE2dStW8wZqGiuLH142n6MKnkLU4ctNLiclw6BZePXFZYIK+AkE
        xQ+k16je5QJBAN0TIKMPWIbbHVr5rkdUqOyezlFFWYOwnMmw/BKa1d3zp54VP/P8
        +5aQ2d4sMoKEOfdWH7UqMe3FszfYFvSu5KMCQFMYeFaaEEP7Jn8rGzfQ5HQd44ek
        lQJqmq6CE2BXbY/i34FuvPcKU70HEEygY6Y9d8J3o6zQ0K9SYNu+pcXt4lkCQA3h
        jJQQe5uEGJTExqed7jllQ0khFJzLMx0K6tj0NeeIzAaGCQz13oo2sCdeGRHO4aDh
        HH6Qlq/6UOV5wP8+GAcCQFgRCcB+hrje8hfEEefHcFpyKH+5g1Eu1k0mLrxK2zd+
        4SlotYRHgPCEubokb2S1zfZDWIXW3HmggnGgM949TlY=
        -----END RSA PRIVATE KEY-----
      verification_key: |
        -----BEGIN PUBLIC KEY-----
        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDHFr+KICms+tuT1OXJwhCUmR2d
        KVy7psa8xzElSyzqx7oJyfJ1JZyOzToj9T5SfTIq396agbHJWVfYphNahvZ/7uMX
        qHxf+ZH9BL1gk9Y6kCnbM5R60gfwjyW1/dQPjOzn9N394zd2FJoFHwdq9Qs0wBug
        spULZVNRxq7veq/fzwIDAQAB
        -----END PUBLIC KEY-----
    cc:
      client_secret: admin
    admin:
      client_secret: admin
    batch:
      username: batchuser
      password: admin
    client:
      autoapprove:
        - cf
    clients:
      cf:
        override: true
        authorized-grant-types: password,implicit,refresh_token
        authorities: uaa.none
        scope: cloud_controller.read,cloud_controller.write,openid,password.write,cloud_controller.admin,scim.read,scim.write
        access-token-validity: 7200
        refresh-token-validity: 1209600
    scim:
      users:
      - admin|admin|scim.write,scim.read,openid,cloud_controller.admin
      - services|admin|scim.write,scim.read,openid,cloud_controller.admin
